### ISSUE TITLE
大佬付费的 已经购买 但是无法下载 

### ISSUE THREAD

**Issue by chaodada** [HarryWang29/tencentKeTang#1]
。。。。可以解析出流地址 但是Ffmpeg 哪一步 就不好使了。。。

**Comment by HarryWang29** [comment]
恩。。。报错应该是找不到ffmpeg把
目前有个问题，如果没有把ffmpeg加到系统path中，会找不到ffmpeg。。。
你可以尝试给ffmpeg创建一个快捷方程式（软链接）到可执行程序所在目录，可能可以解决这个问题
原因是我在写ffmpeg操作时，忘记读取配置文件中的path了。。。

**Comment by HarryWang29** [comment]
上传了新的接口进行解决问题
