### ISSUE TITLE
Mac环境运行报错

### ISSUE THREAD

**Issue by xzajyjs** [HarryWang29/tencentKeTang#18]
```
panic: 调用ffmpeg出错，请检查地址: exec.Run: exec: "ffmpeg": executable file not found in $PATH

goroutine 1 [running]:
crawler/tencentKeTang/config.NewApp(0x1b)
	/Users/harry/app/go/src/crawler/tencentKeTang/config/app.go:33 +0x2ed
main.main()
	/Users/harry/app/go/src/crawler/tencentKeTang/main.go:25 +0x34
```
### 将该目录添加到$PATH后
```
panic: 调用ffmpeg出错，请检查地址: exec.Run: signal: abort trap

goroutine 1 [running]:
crawler/tencentKeTang/config.NewApp(0x1b)
	/Users/harry/app/go/src/crawler/tencentKeTang/config/app.go:33 +0x2ed
main.main()
	/Users/harry/app/go/src/crawler/tencentKeTang/main.go:25 +0x34
```

**Comment by HarryWang29** [comment]
mac环境的话，可以尝试使用brew install ffmpeg来进行安装ffmpeg

**Comment by KHNAHTOE** [comment]
> ```
> panic: 调用ffmpeg出错，请检查地址: exec.Run: exec: "ffmpeg": executable file not found in $PATH
> 
> goroutine 1 [running]:
> crawler/tencentKeTang/config.NewApp(0x1b)
> 	/Users/harry/app/go/src/crawler/tencentKeTang/config/app.go:33 +0x2ed
> main.main()
> 	/Users/harry/app/go/src/crawler/tencentKeTang/main.go:25 +0x34
> ```
> 
> 
>      
>   
> 
> ### 将该目录添加到$PATH后
> 
> ```
> panic: 调用ffmpeg出错，请检查地址: exec.Run: signal: abort trap
> 
> goroutine 1 [running]:
> crawler/tencentKeTang/config.NewApp(0x1b)
> 	/Users/harry/app/go/src/crawler/tencentKeTang/config/app.go:33 +0x2ed
> main.main()
> 	/Users/harry/app/go/src/crawler/tencentKeTang/main.go:25 +0x34
> ```

大佬解决了吗？

**Comment by KHNAHTOE** [comment]
> mac环境的话，可以尝试使用brew install ffmpeg来进行安装ffmpeg

大佬，linux的咋用，我用的windows的下载现在下载不了了，以前还有扫码登录，现在直接自动登录了。

**Comment by HarryWang29** [comment]
> > mac环境的话，可以尝试使用brew install ffmpeg来进行安装ffmpeg
> 
> 大佬，linux的咋用，我用的windows的下载现在下载不了了，以前还有扫码登录，现在直接自动登录了。

后期会直接打包到docker镜像中
