### ISSUE TITLE
大佬执行报错了

### ISSUE THREAD

**Issue by jijianming** [HarryWang29/tencentKeTang#2]
anic: items.Get: json.Unmarshal: json: cannot unmarshal string into Go struct field .result.terms.chapter_info.sub_info.task_info.resid_ext of type struct { Times int "json:\"times\""; Txcloud int "json:\"txcloud\""; Vid string "json:\"vid\"" }

goroutine 1 [running]:
main.main()
	/Users/harry/app/go/src/crawler/tencentKeTang/main.go:35 +0x1f7

**Comment by HarryWang29** [comment]
收到
jijianming ***@***.***> 于 2021年6月5日周六 01:12写道：

**Comment by HarryWang29** [comment]
采用了新的接口进行操作，麻烦再试下

**Comment by jijianming** [comment]
![image](https://user-images.githubusercontent.com/15081733/120986172-e11dde00-c7ae-11eb-92f4-1d073eb2b2e9.png)
这是config配置ffmpeg路径,
报错：
![image](https://user-images.githubusercontent.com/15081733/120986233-f1ce5400-c7ae-11eb-888c-2547308439cd.png)

**Comment by jijianming** [comment]
![Uploading image.png…]()
debug输出

**Comment by HarryWang29** [comment]
汗
看上去有两个错误啊。。。

1. 看上去是腾讯接口没有按照预期返回，这个比较麻烦，我看看是不是补全一下错误信息
2. ffprobe没有找到啊，有正确安装么

**Comment by HarryWang29** [comment]
linux？还是mac？如果已经安装在`/usr/local/bin/`中的话，应该可以不设置path参数

**Comment by jijianming** [comment]
mac,
![image](https://user-images.githubusercontent.com/15081733/121003364-0830db80-c7c0-11eb-9803-ca7fd27feb40.png)

**Comment by HarryWang29** [comment]
确实有点郁闷。。。
如果配置文件中不写ffmpeg的path呢

**Comment by jijianming** [comment]
还是不行

**Comment by HarryWang29** [comment]
最新版本中我在程序启动时就增加了检查，麻烦看下启动时，是否会报错
要是没有报错的话，那应该ffmpeg/ffprobe都没有问题，就是执行参数有问题了
我晚点看看这个执行报错怎么暴露到外层

**Comment by jijianming** [comment]
新版本开启debug日志

url:https://ke.qq.com/cgi-bin/qcloud/get_token?bkn=406332881&fileId=5285890807873564864&t=0.595600&term_id=103299436, method:GET, header:map[Cookie:[pgv_info=ssid=s9891113977; pgv_pvid=9641246420; tdw_data_testid=; tdw_data_flowid=; RK=jcQQ/qdOax; ptcz=8c494ac11e7d6df7aab8b7f7692c5e78fcfcb9fd505e45660033b7bfa2b157fc; lskey=0001000077220d2559381b0f3b0b8b2511fff464a50d43e8764b173fe0cca9c08f2586580dc68ef9e5229157; auth_version=2.0; mix_login_mode=true; tdw_auin_data=-; tdw_first_visited=1; uid_uin=144115200942192727; uid_type=2; openid=oTpUI0ZTJhQHj_WJnGJEf1aSgRaM; uid_appid=1400000008; uid_a2=9578e98a33cda018e74fc4d2e237a43335f04570ef2371b0906bfd9c3bf4894b974230e7af4c4645fcd9b1205b93e3f12bec293b33d94128123b3648a46847a08a7b9adbdef93829; uin=144115200942192727; p_uin=144115200942192727; p_luin=144115200942192727; uid_origin_uid_type=2; ke_login_type=2; ts_uid=9311920520; uin=o0996013797; qqmusic_uin=0996013797; qqmusic_key=@vo1tAaGaB; qqmusic_fromtag=6; rv2=8091100B0496C31F298BBB869032695171E777F9DC1283C818; property20=1251BB2D086CCD82D1896B0EE6DF0F29CCD03094DA615BD9C79FFF4A6721CF53853EEEEED5B647CD; localInterest=[2054]; iswebp=1; ts_refer=www.baidu.com/link; Hm_lvt_0c196c536f609d373a16d246a117fd44=1622765232,1622790601; sessionPath=162279097415724608230246; skey=@8N7LskLC8; ts_last=ke.qq.com/webcourse/index.html; Hm_lpvt_0c196c536f609d373a16d246a117fd44=1622824242; _pathcode=0.8292790097229228; tdw_data={"ver4":"www.baidu.com","ver5":"","ver6":"","refer":"www.baidu.com","from_channel":"","path":"B-0.8292790097229228","auin":"-","uin":"144115200942192727","real_uin":"144115200942192727"}; tdw_data_new_2={"auin":"-","sourcetype":"","sourcefrom":"","uin":"144115200942192727","visitor_id":"7557777522638398","sessionPath":"162279097415724608230246","ver9":"144115200942192727","ver10":"","url_page":"","url_module":"","url_position":""}] Referer:[https://ke.qq.com/webcourse/index.html] User-Agent:[beegoServer]], reqBody:
url:https://ke.qq.com/cgi-bin/qcloud/get_token?bkn=406332881&fileId=5285890807873564864&t=0.595600&term_id=103299436, method:GET, respBody:{"result":{"sign":"9edb8237a5097585e880d60e9970b39c","t":"60e5880b","exper":0,"us":"2963426619025400888"},"retcode":0}
url:https://playvideo.qcloud.com/getplayinfo/v2/1258712167/5285890807873564864?exper=0&sign=9edb8237a5097585e880d60e9970b39c&t=60e5880b&us=2963426619025400888, method:GET, header:map[User-Agent:[beegoServer]], reqBody:
url:https://playvideo.qcloud.com/getplayinfo/v2/1258712167/5285890807873564864?exper=0&sign=9edb8237a5097585e880d60e9970b39c&t=60e5880b&us=2963426619025400888, method:GET, respBody:{"code":0,"message":"","requestId":"4391c367b4b44cfb878c8e9078071500","playerInfo":{"playerId":"401453","name":"default","defaultVideoClassification":"SD","videoClassification":[{"id":"FLU","name":"流畅","definitionList":[10,510,210,610,10046,710]},{"id":"SD","name":"标清","definitionList":[20,520,220,620,10047,720]},{"id":"HD","name":"高清","definitionList":[30,530,230,630,10048,730]},{"id":"FHD","name":"全高清","definitionList":[40,540,240,640,10049,740]},{"id":"2K","name":"2K","definitionList":[70,570,270,670,370,770]},{"id":"4K","name":"4K","definitionList":[80,580,280,680,380,780]},{"id":"AUDIO","name":"纯音频","definitionList":[1100,1110,1120,1130,1140,1010,1020]}],"logoLocation":"1","logoPic":"","logoUrl":"","patchInfo":[{"location":0,"link":"","type":"0","url":""},{"location":1,"link":"","type":"0","url":""},{"location":2,"link":"","type":"0","url":""}]},"coverInfo":{"coverUrl":"https://1258712167.vod2.myqcloud.com/25121a6avodtransbj1258712167/6a2fcdfc5285890807873564864/coverBySnapshot_10_0.jpg?t=60e5880b&exper=0&us=2963426619025400888&sign=aa80e7d8e61e93f20771cbd9d6a93f74"},"videoInfo":{"basicInfo":{"name":"产品","description":"","tags":[]},"drm":{"definition":10},"masterPlayList":{"idrAligned":false,"url":"https://1258712167.vod2.myqcloud.com/25121a6avodtransbj1258712167/6a2fcdfc5285890807873564864/drm/master_playlist.m3u8?t=60e5880b&exper=0&us=2963426619025400888&sign=c07423a9436840e6dcf6f2001de6d7fa","definition":10000,"md5":"dc9ed42000178eaf84cc650d1a7bc75f"},"transcodeList":[{"url":"https://1258712167.vod2.myqcloud.com/25121a6avodtransbj1258712167/6a2fcdfc5285890807873564864/drm/v.f30739.m3u8?t=60e5880b&exper=0&us=2963426619025400888&sign=c07423a9436840e6dcf6f2001de6d7fa","definition":30739,"duration":6539,"floatDuration":6539.669921875,"size":275276731,"totalSize":275276731,"bitrate":336444,"height":270,"width":378,"container":"hls,applehttp","md5":"741e02fa10067721e09c9a104d64004e","videoStreamList":[{"bitrate":291655,"codec":"h264","fps":15,"height":270,"width":378}],"audioStreamList":[{"bitrate":44789,"codec":"aac","samplingRate":44100}],"templateName":"kt_flu"},{"url":"https://1258712167.vod2.myqcloud.com/25121a6avodtransbj1258712167/6a2fcdfc5285890807873564864/drm/v.f30740.m3u8?t=60e5880b&exper=0&us=2963426619025400888&sign=c07423a9436840e6dcf6f2001de6d7fa","definition":30740,"duration":6539,"floatDuration":6539.669921875,"size":469710909,"totalSize":469710909,"bitrate":574295,"height":480,"width":672,"container":"hls,applehttp","md5":"9b1c89eeac5da29e48aa00d7595d773c","videoStreamList":[{"bitrate":529506,"codec":"h264","fps":15,"height":480,"width":672}],"audioStreamList":[{"bitrate":44789,"codec":"aac","samplingRate":44100}],"templateName":"kt_sd"},{"url":"https://1258712167.vod2.myqcloud.com/25121a6avodtransbj1258712167/6a2fcdfc5285890807873564864/drm/v.f56149.m3u8?t=60e5880b&exper=0&us=2963426619025400888&sign=c07423a9436840e6dcf6f2001de6d7fa","definition":56149,"duration":6539,"floatDuration":6539.669921875,"size":830215109,"totalSize":830215109,"bitrate":1015402,"height":628,"width":880,"container":"hls,applehttp","md5":"d87be3d6cb39896093e7ef52c10ff244","videoStreamList":[{"bitrate":970613,"codec":"h264","fps":15,"height":628,"width":880}],"audioStreamList":[{"bitrate":44789,"codec":"aac","samplingRate":44100}],"templateName":"edu_ke_hd_raw"},{"url":"https://1258712167.vod2.myqcloud.com/25121a6avodtransbj1258712167/6a2fcdfc5285890807873564864/drm/v.f30741.m3u8?t=60e5880b&exper=0&us=2963426619025400888&sign=c07423a9436840e6dcf6f2001de6d7fa","definition":30741,"duration":6539,"floatDuration":6539.669921875,"size":885919497,"totalSize":885919497,"bitrate":1083441,"height":720,"width":1008,"container":"hls,applehttp","md5":"944841d4e9f45c59db2970f2655570bc","videoStreamList":[{"bitrate":1038652,"codec":"h264","fps":15,"height":720,"width":1008}],"audioStreamList":[{"bitrate":44789,"codec":"aac","samplingRate":44100}],"templateName":"kt_hd"}]}}

2021/06/07 18:55:08 download err:ffmpeg.Do: probe: exec.Run: exit status 1

**Comment by HarryWang29** [comment]
你好，我把上面那个回复删除了，暴露了cookie，我查看了一下，目前估计是你的cookie和我的cookie并不相同，组成部分有些不一致，导致最后拼接视频连接的时候，出现错误

**Comment by HarryWang29** [comment]
看来我现在的拼接方式应该是只能支持帐号密码登录，不知道是否方便测试一下

**Comment by jijianming** [comment]
那我知道为啥了、我的是微信扫码登录的。。。可能是这个问题。

**Comment by HarryWang29** [comment]
好的，我这边看下后面支持下

**Comment by jijianming** [comment]
大佬牛逼。还有QQ扫描登录的。

**Comment by HarryWang29** [comment]
微信扫码登录已支持

**Comment by jijianming** [comment]
可以了，大佬。就是有点耗cpu。
![image](https://user-images.githubusercontent.com/15081733/121015667-d1fa5880-c7cd-11eb-8981-7e19b9a64749.png)

**Comment by HarryWang29** [comment]
这个是ffmpeg的事情了，mac的话，也可以使用gpu加速，效率提升两三倍是可以的

jijianming ***@***.***> 于 2021年6月7日周一 20:21写道：

**Comment by jijianming** [comment]
明白。回去试试。大佬牛逼
