### ISSUE TITLE
大佬你好，我想单独下载某一个视频，命令打的d -t 131，但是有报错，请问是我哪里做的不对么？

### ISSUE THREAD

**Issue by linyingge** [HarryWang29/tencentKeTang#24]
TencentKeTang:***$ d -t 131
Incorrect Usage: flag provided but not defined: -t

NAME:
   tencentKeTang-windows-386.exe download - 下载文件

USAGE:
   TencentKeTang download <cid>

DESCRIPTION:
   下载文件默认保存到当前目录的download目录
       可输入cid直接下载全部内容
       若不填写 flag 则通过tree中的序号下载（支持多序号下载）

       示例：
       TencentKeTang d -c 123456
       TencentKeTang d 1
       TencentKeTang d 1 2 3 4

OPTIONS:
   --cid value, -c value  通过cid下载
   --help, -h             show help (default: false)

**Comment by HarryWang29** [comment]
可以使用，如下命令先进行列目录
```bash
tree -c xxx -t yyy
```
再使用`download`命令索引下载
```bash
d 1
```
