### ISSUE TITLE
大佬你好，请教一个问题，下载下来的视频是不是会经过压缩，文件大小和自己手机缓存的大小差别有点大

### ISSUE THREAD

**Issue by zhengkkk** [HarryWang29/tencentKeTang#25]

**Comment by HarryWang29** [comment]
是小了？这个地方我记得确实是需要有个优化项，我记得当时默认获取的是数组最后一个，但是并没有判断是否是最高画质

**Comment by 2kkkkkk** [comment]
> 是小了？

是小了很多，我看进度条时间是一样的，但我手机缓存1.7G，用工具下载400多M，有的只有300多M

**Comment by HarryWang29** [comment]
好吧，等有空了看看……

**Comment by HarryWang29** [comment]
> > 是小了？
> 
> 是小了很多，我看进度条时间是一样的，但我手机缓存1.7G，用工具下载400多M，有的只有300多M

后来确实发现了这个问题，处理方式已经想好
