### ISSUE TITLE
window双击exe闪退

### ISSUE THREAD

**Issue by Caryio** [HarryWang29/tencentKeTang#30]
大佬好！我下载了0.2.5版本的[tencentKeTang-windows-amd64.zip](https://github.com/HarryWang29/tencentKeTang/files/9077491/tencentKeTang-windows-amd64.zip)和
[tencentKeTang-windows-386.zip](https://github.com/HarryWang29/tencentKeTang/files/9077492/tencentKeTang-windows-386.zip)
里面有一个config配置文件和一个exe，但两个版本的exe文件均无法双击打开（闪退）

设备版本：
win10 21H2 19044.1826，python3.10.5

直接用cmd的话，会显示找不到tencentKeTang这个命令/不是内部命令，即使cd打开所在的文件夹也不行。

请大佬指点，感谢！

**Comment by HarryWang29** [comment]
是不是没有ffmpeg?

**Comment by Caryio** [comment]
> 

感谢大佬回复！是我把ffmpeg环境变量弄错了。。。我现在成功双击打开了，也成功用tree -c xxxx打开了列表，但是执行d -c xxxx出现了新的错误，请指点，非常感谢！（arm64、368报错相同）


[hls @ 0000020618bb4400] Skip ('#EXT-X-VERSION:3')
[hls @ 0000020618bb4400] Opening 'https://ke.qq.com/cgi-bin/qcloud/get_dk?edk=CiBacYAXzp5VqGABlOlrlRlJdkr5YYxUKrUtNO0jjwu7ZRCO08TAChiaoOvUBCokOTMyNDg4YmItOWZjYS00MzFiLWJiYjItNjFmMDhjYjNlYmM3&fileId=5285890799113953364&keySource=VodBuildInKMS&token=dWluPTEzMzcyNzc1MTc7c2tleT07cHNrZXk9O3Bsc2tleT07ZXh0PTt1aWRfdHlwZT0wO3VpZF9vcmlnaW5fdWlkX3R5cGU9MTAxMjtjaWQ9ODU3NzUxO3Rlcm1faWQ9MTAwOTU2MTYxO3ZvZF90eXBlPTA%3D' for reading
[hls @ 0000020618bb4400] Opening 'crypto+https://1258712167.vod2.myqcloud.com/fb8e6c92vodtranscq1258712167/41e3c6365285890799113953364/drm/v.f30741.ts?start=0&end=1016895&type=mpegts&exper=0&sign=ca277fcf4753503c34a6b42b0b1f89f7&t=62fc8e6d&us=5059664849239849018' for reading
[hls @ 0000020618bb4400] Opening 'crypto+https://1258712167.vod2.myqcloud.com/fb8e6c92vodtranscq1258712167/41e3c6365285890799113953364/drm/v.f30741.ts?start=1016896&end=2280639&type=mpegts&exper=0&sign=ca277fcf4753503c34a6b42b0b1f89f7&t=62fc8e6d&us=5059664849239849018' for reading
[hls @ 0000020618bb4400] Error when loading first segment 'https://1258712167.vod2.myqcloud.com/fb8e6c92vodtranscq1258712167/41e3c6365285890799113953364/drm/v.f30741.ts?start=0&end=1016895&type=mpegts&exper=0&sign=ca277fcf4753503c34a6b42b0b1f89f7&t=62fc8e6d&us=5059664849239849018'
https://1258712167.vod2.myqcloud.com/fb8e6c92vodtranscq1258712167/41e3c6365285890799113953364/drm/voddrm.token.dWluPTEzMzcyNzc1MTc7c2tleT07cHNrZXk9O3Bsc2tleT07ZXh0PTt1aWRfdHlwZT0wO3VpZF9vcmlnaW5fdWlkX3R5cGU9MTAxMjtjaWQ9ODU3NzUxO3Rlcm1faWQ9MTAwOTU2MTYxO3ZvZF90eXBlPTA=.v.f30741.m3u8?t=62fc8e6d&exper=0&us=5059664849239849018&sign=ca277fcf4753503c34a6b42b0b1f89f7: Invalid data found when processing input
: exit status 1

具体情况如下图所示：
![image](https://user-images.githubusercontent.com/41476501/179457880-cb4a1239-4d46-4572-8f60-b8268c4c8327.png)


我的ffmpeg版本：version: 2022-07-14-git-882aac99d2，从这里https://www.gyan.dev/ffmpeg/builds/ 下载的

**Comment by Caryio** [comment]
抱歉忘记说，我是用cookie登录的，具体config如下：

![image](https://user-images.githubusercontent.com/41476501/179458666-80b8b9f5-9eac-41b8-b301-3fea98f01956.png)


或者，ffmpeg使用参数必须设置吗？不加速无法下载，之类的原因？

感谢回复！

**Comment by Caryio** [comment]
> 稍微看了下，你这里报错的连接使用几个播放器都无法正常打开，在腾讯课堂中这个视屏能够正常打开么？ 还有一个可能，不过我无法确定，会不会是你cookie弄出来之后，cookie被刷新了？
> […](#)
> On Jul 18, 2022, 2:55 PM +0800, CaryioCAT ***@***.***>, wrote: 抱歉忘记说，我是用cookie登录的，具体config如下： 或者，ffmpeg使用参数必须设置吗？不加速无法下载，之类的原因？ 感谢回复！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

感谢回复。

我可以正常在腾讯课堂web端观看，是我们学校老师开的课；cookie我又对比了一下，Request URL: https://ke.qq.com/cgi-bin/identity/info 中的cookie没有变化，我每次复制cookie是从开始的'RK='一直复制到最后一个右括号'}'，关闭浏览器重新打开，cookie没有变化；一直都是管理员打开。

哎，我太菜了……麻烦大佬再指点一下

（or会不会是我有什么愚蠢的操作错误？我录了个gif ↓）

![动画](https://user-images.githubusercontent.com/41476501/179462758-febe3b07-003f-466d-aad2-79ed108baa33.gif)

**Comment by HarryWang29** [comment]
操作上应该没什么问题，cookie复制上，尝试使用cookie: “需要复制的内容”，从network中，cookie全部内容都复制一下，我看了下我这里的cookie，RK必填值之前，还有个 `pgv_pvid` 字段

**Comment by Caryio** [comment]
> 操作上应该没什么问题，cookie复制上，尝试使用cookie: “需要复制的内容”，从network中，cookie全部内容都复制一下，我看了下我这里的cookie，RK必填值之前，还有个 `pgv_pvid` 字段
> […](#)
> On Jul 18, 2022, 3:26 PM +0800, CaryioCAT ***@***.***>, wrote: > 稍微看了下，你这里报错的连接使用几个播放器都无法正常打开，在腾讯课堂中这个视屏能够正常打开么？ 还有一个可能，不过我无法确定，会不会是你cookie弄出来之后，cookie被刷新了？ > … > On Jul 18, 2022, 2:55 PM +0800, CaryioCAT @.>, wrote: 抱歉忘记说，我是用cookie登录的，具体config如下： 或者，ffmpeg使用参数必须设置吗？不加速无法下载，之类的原因？ 感谢回复！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 感谢回复。 我可以正常在腾讯课堂web端观看，是我们学校老师开的课；cookie我又对比了一下，Request URL: https://ke.qq.com/cgi-bin/identity/info 中的cookie没有变化，我每次复制cookie是从开始的'RK='一直复制到最后一个右括号'}'，关闭浏览器重新打开，cookie没有变化；一直都是管理员打开。 哎，我太菜了……麻烦大佬再指点一下 （or会不会是我有什么愚蠢的操作错误？我录了个gif ↓） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

  大佬，我直接右击cookie，有一个“复制值”，用的这个，可以吗？

* 我的cookie中`RK`是在最前面，`pgv_pvid` 在后面

![image](https://user-images.githubusercontent.com/41476501/179468473-e7d01aac-6173-45a2-9952-647ab6df2a30.png)



* 请问`尝试使用cookie: “需要复制的内容”`具体是指什么呢？可否具体指点一下，谢谢！我只有一个右键“复制值”


![image](https://user-images.githubusercontent.com/41476501/179468811-4b32291b-d000-460f-b038-b156d31dc89a.png)

**Comment by Caryio** [comment]
大佬，我捣鼓了一下午到现在，貌似找到了原因。

我找了一个免费课程，操作与我之前完全相同，下载成功了。
> 不过下载过程中命令行里一直显示100%，但实际上正在下载中，不断地右键属性可以看到文件正在变大。

而我学校的课程，是付费课程，就一直没有下载成功。
>   但我的账号是拥有这个课程的，可以正常在web端观看，学校那边给所有上这个课的同学加的权限

所以我猜测，可能是接口问题/token加密/AES加密/腾讯自己的定制加密之类的问题，完全是针对付费课程（即使该账号拥有权限）

**Comment by Caryio** [comment]
> 操作上应该没什么问题，cookie复制上，尝试使用cookie: “需要复制的内容”，从network中，cookie全部内容都复制一下，我看了下我这里的cookie，RK必填值之前，还有个 `pgv_pvid` 字段
> […](#)
> On Jul 18, 2022, 3:26 PM +0800, CaryioCAT ***@***.***>, wrote: > 稍微看了下，你这里报错的连接使用几个播放器都无法正常打开，在腾讯课堂中这个视屏能够正常打开么？ 还有一个可能，不过我无法确定，会不会是你cookie弄出来之后，cookie被刷新了？ > … > On Jul 18, 2022, 2:55 PM +0800, CaryioCAT @.>, wrote: 抱歉忘记说，我是用cookie登录的，具体config如下： 或者，ffmpeg使用参数必须设置吗？不加速无法下载，之类的原因？ 感谢回复！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 感谢回复。 我可以正常在腾讯课堂web端观看，是我们学校老师开的课；cookie我又对比了一下，Request URL: https://ke.qq.com/cgi-bin/identity/info 中的cookie没有变化，我每次复制cookie是从开始的'RK='一直复制到最后一个右括号'}'，关闭浏览器重新打开，cookie没有变化；一直都是管理员打开。 哎，我太菜了……麻烦大佬再指点一下 （or会不会是我有什么愚蠢的操作错误？我录了个gif ↓） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

大佬，我捣鼓了一下午到现在，貌似找到了原因。

我找了一个免费课程，操作与我之前完全相同，下载成功了。
> 不过下载过程中命令行里一直显示100%，但实际上正在下载中，不断地右键菜单查看属性可以看到文件正在变大。

而我学校的课程，是付费课程，就一直没有下载成功。
> 但我的账号是拥有这个课程的，可以正常在web端观看，学校那边给所有上这个课的同学加的权限

所以我猜测，可能是接口问题/token加密/AES加密/腾讯自己的定制加密之类的问题，完全是针对付费课程（即使该账号拥有权限）

**Comment by HarryWang29** [comment]
嗯，关于这个进度条确实也有问题，也想了其他的方案进行优化，不过目前是没有时间去弄
你说的这种学校给开的权限的话，可能需要专门调试才行，估计是我没有遇到这种情况，所以没有做专门的应对
