### ISSUE TITLE
新版本下载完成后合并问题

### ISSUE THREAD

**Issue by D-en1997** [HarryWang29/tencentKeTang#32]
新版本确实速度快乐很多，下载完成后合并出现问题了，应该是没有合并，批量下载的时候，只合并了第一个视频，如下图
这个文件夹应该是整个视频的所有片段嘛？？我们可不可以使用工具自己合并？
![image](https://user-images.githubusercontent.com/36223295/180589765-dba0f4ab-0502-4893-9fdd-c16d6f91769c.png)
![image](https://user-images.githubusercontent.com/36223295/180589780-44eb5cce-5e13-49ee-8963-42a5d4815cfe.png)

**Comment by HarryWang29** [comment]
![image](https://user-images.githubusercontent.com/8288067/180918794-a9f576bf-ded2-4ce6-9f95-d46a7646f2fd.png)
