### ISSUE TITLE
win平台0.2.8下载报错

### ISSUE THREAD

**Issue by 15876555512** [HarryWang29/tencentKeTang#36]
2022/07/26 23:36:39 getVodUrl err: keTang.MediaInfo: video_auth_error
2022/07/26 23:36:39 getVodUrl err: keTang.MediaInfo: video_auth_error
2022/07/26 23:36:39 getVodUrl err: keTang.MediaInfo: video_auth_error
2022/07/26 23:36:39 getVodUrl err: keTang.MediaInfo: video_auth_error
2022/07/26 23:36:39 getVodUrl err: keTang.MediaInfo: video_auth_error
2022/07/26 23:36:39 getVodUrl err: keTang.MediaInfo: video_auth_error

用的微信登录的ck下的付费的课程  不知道是什么问题呢？

**Comment by HarryWang29** [comment]
昨天发现，扫码登录存在问题，可使用cookie的方式进行下载

**Comment by HarryWang29** [comment]
#35
