### ISSUE TITLE
Windows平台0.2.8 m3u8文件合成问题

### ISSUE THREAD

**Issue by Kevin-HYX** [HarryWang29/tencentKeTang#37]
- 测试了大批量下载，结果大多数文件都正常下下来了，极少部分文件只合成了一半不到就停止合成了，m3u8文件夹也没有被删除
- bug很隐蔽，我重复下载以上出错的文件，这个bug却没有复现，小批量下载没有此问题，估计是大批量下载时某些线程被意外终止了。
- 文件大小都在1G左右（约合一小时时长），小文件下载也没出现过这个问题

**Comment by HarryWang29** [comment]
合成一半就停止应该是ffmpeg报错了，所以中止了合并，晚点我把这个地方处理一下，也只能展示出来，人工重试处理了
