### ISSUE TITLE
大佬，win版无法下载呢

### ISSUE THREAD

**Issue by 78421276** [HarryWang29/tencentKeTang#4]
getVodUrl err: keTang.MediaInfo: get: json.Unmarshal,resp:: unexpected end of JSON input
![Snipaste_2021-07-06_12-19-47](https://user-images.githubusercontent.com/81909574/124541750-a6ae6c00-de54-11eb-9959-d5cc65517dcf.png)

**Comment by HarryWang29** [comment]
有点郁闷，我看下把，之前确实也发现过，腾讯的一些接口字段类型是动态的，能提供视频的链接么？

**Comment by HarryWang29** [comment]
看了下，这个报错像是获取视频时，认证失败了，`https://playvideo.qcloud.com/getplayinfo/v2/1258712167/` 接口应答失败了，难道1258712167还有别的值么？这个也是我没有找到的一个东西
