### ISSUE TITLE
0.2.9 m3u8文件不合成

### ISSUE THREAD

**Issue by Kevin-HYX** [HarryWang29/tencentKeTang#42]

**Comment by Kevin-HYX** [comment]
![image](https://user-images.githubusercontent.com/51521949/182021867-04d093aa-43e0-4e18-a2f0-99b5e9772c02.png)
下载完m3u8线程貌似就终止了，也不合成mp4，只留下一个m3u8文件夹
测试了多次，都是这个情况

**Comment by LoveyCat** [comment]
Unable to read key file
