### ISSUE TITLE
v0.2.10下载bug

### ISSUE THREAD

**Issue by lucifnce** [HarryWang29/tencentKeTang#43]
登录方式cookie 版本v.0.2.10
Bug_1 运行命令 d -c 未按照课程目录顺序下载，如图所示，下载完01 直接跳到下载 04 
![image](https://user-images.githubusercontent.com/24662791/182301687-fa9a1d23-5a09-4964-9965-571510b96612.png)

Bug_2  继bug_1 下载 04合成之后 突然不下载了，重启软件后 出现下面bug
![image](https://user-images.githubusercontent.com/24662791/182302221-564581ea-25a2-472f-abfe-e415073ffcdd.png)

**Comment by HarryWang29** [comment]
这个课程我看了一下，如果你已经购买了此课程，那么需要检查cookie的完整性，如果你没有购买此课程，此软件无法帮你下载课程
