### ISSUE TITLE
已买课程不能下载

### ISSUE THREAD

**Issue by zhongheng666** [HarryWang29/tencentKeTang#44]
已买课程不能下载，只能下载到免费部分。
收费部分提示 getVodUrl err: keTang.MediaInfo: video_auth_error

**Comment by HarryWang29** [comment]
目前扫码登录都无法正常使用，使用cookie方式

**Comment by zhongheng666** [comment]
> 目前扫码登录都无法正常使用，使用cookie方式

就是使用网页 document.cookie导出的cookie........

**Comment by linyingge** [comment]
我的也是这个报错，用cookie的登录方式，只能下载免费的部分

**Comment by zhongheng666** [comment]
> 
重新提个issue吧，这个作者直接给关了

**Comment by linyingge** [comment]
ok
