### ISSUE TITLE
建议自动按照章节增加序号

### ISSUE THREAD

**Issue by DaTeToMe** [HarryWang29/tencentKeTang#5]
没有序号，视频排序起来都是乱的

**Comment by HarryWang29** [comment]
序号问题确实存在，我前几天自己下载视频的时候，也发现这个有点不方便
由于视频是线性下载的，所以目前解决办法是可以通过创建时间排序

**Comment by DaTeToMe** [comment]
![image](https://user-images.githubusercontent.com/35985808/126749507-c201e4bb-0288-4368-a2a4-7719b865f0aa.png)
下载默认的是下面这个标题，大佬应该可以调整看看

**Comment by HarryWang29** [comment]
今天发版的时候也考虑过是否要一起解决这个问题
不过确实没有想好怎么做，如果是通过cid批量下载，那么可以获取序号
但是个别下载的话，就不太好搞了
能提供一下连接么？我看下腾讯是否有返回相应的东西

**Comment by DaTeToMe** [comment]
https://ke.qq.com/course/410351?taid=3517548151063279

**Comment by DaTeToMe** [comment]
![image](https://user-images.githubusercontent.com/35985808/126750856-494a0178-b415-42b1-a26a-eb4789f5af7a.png)

**Comment by HarryWang29** [comment]
刚才看了下，确实是有地方能够获得序号，不过要晚点再看看怎么处理好一点

**Comment by DaTeToMe** [comment]
大佬加油

**Comment by DaTeToMe** [comment]
差点忘记了，还有可以根据课程标题创建一个文件夹，下载的课程多了怕叠在一起了

**Comment by HarryWang29** [comment]
这个本来是在计划中的，好像忘记做了。。。后面一起补上把
