### ISSUE TITLE
下载速度有待提高、还请大佬能不能想办法解决一下！

### ISSUE THREAD

**Issue by lucifnce** [HarryWang29/tencentKeTang#6]
首先 鸣谢 大佬开发了此软件工具、辛苦~~
摸索了一会，也会用了！实用方法比较简单，可就是下载的速度确实有待提高...
不知道你们网速 如何 ，我移动300M的光纤都跑步起来网速，555~~~

**Comment by HarryWang29** [comment]
哈哈，能够造福大家是最好的
你可以观察一下，如果你使用的时候是cpu很高，但是显卡没有使用的话
建议你查看一下如何开启gpu加速，我初步观察的话，效率提升将近10倍，还是我垃圾集显测的

**Comment by jijianming** [comment]
你需要配置下gpu加速，我配置后，立马效果上去了，

**Comment by adinghub** [comment]
> 你需要配置下gpu加速，我配置后，立马效果上去了，

您好，我不太了解ffmpeg，请问这如何配置GPU呢？Google后没有找到解决方案。

**Comment by adinghub** [comment]
> 



> 哈哈，能够造福大家是最好的 你可以观察一下，如果你使用的时候是cpu很高，但是显卡没有使用的话 建议你查看一下如何开启gpu加速，我初步观察的话，效率提升将近10倍，还是我垃圾集显测的
> […](#)
> On Jul 20, 2021, 4:59 AM +0800, lucifnce ***@***.***>, wrote: 首先 鸣谢 大佬开发了此软件工具、辛苦~~ 摸索了一会，也会用了！实用方法比较简单，可就是下载的速度确实有待提高... 不知道你们网速 如何 ，我移动300M的光纤都跑步起来网速，555~~~ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，我不太了解ffmpeg，请问这如何配置GPU呢？Google后没有找到解决方案。

![image](https://user-images.githubusercontent.com/55272270/157373118-84aa965d-ac7e-462a-a645-7e9e629b0a96.png)

**Comment by longhorn217054** [comment]
将参数改为params: '-c copy'就不会下载的同时重新编码，不会额外消耗CPU和GPU资源。下载速递提升非常明显

**Comment by longhorn217054** [comment]
如果要N卡转换h264就换成params: '-c:v h264_nvenc'

**Comment by HarryWang29** [comment]
可关注后续版本  #29
