### ISSUE TITLE
大佬，能不能解决一些有些课程是特殊字符的问题

### ISSUE THREAD

**Issue by skrjinn** [HarryWang29/tencentKeTang#7]
我有些付费课程没有看完，想下过来看，但是课程名里面有问号（这一些特殊字符），导致下载的时候无法创建本地文件，这个能优化一下吗，比如用序号代替就可以了，万分感谢。
download err:ffmpeg.Do: os.Stat: CreateFile ./download//为什么是python?（建筑+风景+规划）.mp4: The filename, directory name, or volume label syntax is incorrect.

**Comment by HarryWang29** [comment]
呃，这确实是一个问题，要想一下如何处理，windows和macos对文件名称的限制还不一样
能提供一下你的课程观看连接么？我看下接口的返回

**Comment by skrjinn** [comment]
我那个是付费课程，共享不了，我找了一个也有带问号的课程
https://ke.qq.com/course/361727?taid=11906207690622207
不过我那个课程名称还有/<>[] +字符 o(╥﹏╥)o

**Comment by HarryWang29** [comment]
没事，有链接就好，我不用看内容，我看看目录就好

skrjinn ***@***.***> 于 2021年7月21日周三 18:33写道：

**Comment by skrjinn** [comment]
好的大佬
https://ke.qq.com/course/183454
https://ke.qq.com/course/275821

**Comment by HarryWang29** [comment]
多谢，不过我估计要晚点才能够处理

**Comment by skrjinn** [comment]
谢谢大佬，您有空能解决就行

**Comment by HarryWang29** [comment]
f4ca7e166b82e355392c718651e3550254999364
