### ISSUE TITLE
大佬，我试了最新版，课程名中有/的还是不是，程序会闪退

### ISSUE THREAD

**Issue by skrjinn** [HarryWang29/tencentKeTang#8]
大佬，我试了最新版，课程名中有/的还是不行，程序会闪退
https://ke.qq.com/course/275821
实在不好意思，再次打扰你(。・＿・。)ﾉI’m sorry~
您有空的时候解决一下就好，谢谢。

**Comment by HarryWang29** [comment]
好的

skrjinn ***@***.***> 于 2021年7月23日周五 23:20写道：

**Comment by Janet-Baker** [comment]
你要是看一眼Windows命名规则就知道了，` \ / : * ? " < > | ` 这9个是不能被用于文件名的……
你要是实在想用，可以用全角字符或者换成别的。
