### ISSUE TITLE
新版本下载报错

### ISSUE THREAD

**Issue by jijianming** [HarryWang29/tencentKeTang#9]
![image](https://user-images.githubusercontent.com/15081733/126885956-2e2d24e6-1ba5-4679-af0c-4ac2bb864d86.png)

**Comment by HarryWang29** [comment]
收到

jijianming ***@***.***> 于 2021年7月25日周日 10:45写道：

**Comment by HarryWang29** [comment]
声明一下：此软件只是做到下载视频到本地观看，并不是突破腾讯课堂的观看限制

这个问题我查看了一下，腾讯课堂报错如下 `{"result":{"err_code":101,"err_msg":"未购买此课程，请购买后听课。"}` 
我增加一下此问题的处理
